# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - setup
  - build
  - test
  - deploy


## --------------
## Setup Process
## --------------

setup:npm:
  stage: setup
  script:
    - npm install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/

## --------------
## Build Project
## --------------

build:npm:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - lib/
  dependencies:
    - setup:npm

## ------------
## Test Project
## ------------
test:lint:
  stage: test
  script:
    - npm run lint
  dependencies:
    - build:npm


test:jasmine:
  stage: test
  script:
    - npm run test
  dependencies:
    - build:npm