# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy


## --------------
## Builds Project
## --------------

build:npm:
  stage: build
  script:
    - npm install
    - npm run compile
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
      - lib/

## ------------
## Test Project
## ------------
test:lint:
  stage: test
  script:
    - npm run lint
  dependencies:
    - build:npm


test:jasmine:
  stage: test
  script:
    - npm run test
  dependencies:
    - build:npm